on:

  push:
    branches:
      - main

env:

  DOCKERHUB_NAMESPACE: c0750688
  DOCKERHUB_REPOSITORY: assignment
  DOCKERHUB_TEST_REPOSITORY: assignment-test
  IMAGE_VERSION: v1.0.0

jobs:

  # 1: Build Docker Image
  build-docker-image:
    name: Build Docker Image
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Builder Docker Main Image
        run: docker build -t ${DOCKERHUB_NAMESPACE}/${DOCKERHUB_REPOSITORY}:${IMAGE_VERSION} -f Dockerfile .
      - name: Push Docker Main Image
        run: docker push ${DOCKERHUB_NAMESPACE}/${DOCKERHUB_REPOSITORY}:${IMAGE_VERSION}
      - name: Build Test Docker Image
        run: |
          mv .dockerignore .dockerignore.temp
          docker build -t ${DOCKERHUB_NAMESPACE}/${DOCKERHUB_TEST_REPOSITORY}:${IMAGE_VERSION} -f DockerfileTest .
          mv .dockerignore.temp .dockerignore
      - name: Push Test Docker Image
        run: docker push ${DOCKERHUB_NAMESPACE}/${DOCKERHUB_TEST_REPOSITORY}:${IMAGE_VERSION}

  # 2: Unit Testing
  unittest:
    name: Unit Testing
    needs: [build-docker-image]
    runs-on: self-hosted
    environment: development
    steps:
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Pull Test Docker Image
        run: docker pull $DOCKERHUB_NAMESPACE/$DOCKERHUB_TEST_REPOSITORY:$IMAGE_VERSION
      - name: Run Test Docker Image
        run: |
          docker run --rm \
            -e MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }} \
            -e MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }} \
            $DOCKERHUB_NAMESPACE/$DOCKERHUB_TEST_REPOSITORY:$IMAGE_VERSION